TEST_URLs = [
        "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Rottweiler_puppy_-21603071920.jpg/640px-Rottweiler_puppy_-21603071920.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/b/ba/Day_354_-_West_Midlands_Police_-_Newly_born_police_puppies_%288288060774%29.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/6/64/4_Puppies_in_a_basket.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/b/be/Aladdin_Loki_puppies_blue_eyes.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/8/8e/Entlebucher_Puppy_on_lawn.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/9/9e/Cute_puppy_dog.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/c/cd/Feeding_puppies_dog.JPG",
        "https://upload.wikimedia.org/wikipedia/commons/3/3b/Boxer_puppy_.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/d/d8/Poodle_Puppy_-_Green_eyes.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/8/8b/Barbarella_the_Chinese_crested_puppy_%2872387%29.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/a/a4/Puppies_suckling_their_mother_in_Kenya.jpg  ",
        "https://upload.wikimedia.org/wikipedia/commons/5/5b/Barbarella_the_Chinese_crested_puppy_%2872353%29.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/b/ba/Dog_puppies_family.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/2/26/Barbarella_the_Chinese_crested_puppy_%2812950%29.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/1/1f/Barbarella_the_Chinese_crested_puppy_%2872390%29.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/8/81/Barbarella_the_Chinese_crested_puppy_%2872339%29.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/1/11/Puppies_sleeping.JPG",
        "https://upload.wikimedia.org/wikipedia/commons/c/c7/Puppies_two.JPG",
        "https://upload.wikimedia.org/wikipedia/commons/5/50/Feeding_puppy_dogs.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/8/8d/Two_puppies_playing_together_one_standing_over_the_other_at_golden_hour_in_Don_Det_Laos.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/7/74/Puppy_filtered.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/6/67/Barbarella_the_Chinese_crested_puppy_%2812929%29.jpg",
]

TEST_QUERY = "https://upload.wikimedia.org/wikipedia/commons/a/aa/Cute_puppy%283%29.jpg"